options=gaoptimset('CreationFcn', @get_population, ...
                   'PopulationSize', 40, ...
                   'MutationFcn', @mutate_swap, ...
                   'Generations', 100, ...
                   'StallGenLimit', inf, ...
                   'StallTimeLimit', inf', ...
                   'SelectionFcn', {@selectiontournament, 4}, ...
                   'CrossoverFcn', @cut_and_crossfill, ...
                   'FitnessLimit', 0, ...
                   'CrossoverFraction', 0.2, ...
                   'EliteCount', 0);

N = 4;
[bestsolution, bestfitness]=ga(@fitness, N, options);
disp(bestsolution)
disp(bestfitness)
